### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by mikhail2015** [sufehmi/AhadPOS2#4]
pada saat kita klik menu laporan keluar pesan berikut: 

Warning: include(../../config/config.php) [function.include]: failed to open stream: No such file or directory in C:\xampp\htdocs\ahadpos\sistem\modul\mod_laporan.php on line 17

Warning: include() [function.include]: Failed opening '../../config/config.php' for inclusion (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\ahadpos\sistem\modul\mod_laporan.php on line 17

**Comment by sufehmi** [comment]
Silakan lakukan sbb :

(1) Buka file mod_laporan.php

(2) Cari baris sbb :

include "../config/config.php";

(3) Ganti menjadi :

include "../../config/config.php";

Selesai.

Selamat mencoba.

**Comment by mikhail2015** [comment]
Sudah saya lakukan seperti itu, tapi masih tetap aja pak. Kalo kita klik
laporan ada muncul seperti itu. Apa harus saya ganti seperti di modul
barang pake kondisi?

**Comment by sufehmi** [comment]
Saya menemukan di situs ahadpos.com, ternyata ada yang mengalami masalah serupa.

Dan solusinya adalah dengan mengganti baris tsb menjadi sbb :

include "/../config/config.php";

Nampaknya ini masalah spesifik di Windows / XAMPP, karena di Linux
tidak masalah.

Juga, pastikan Anda mendapatkan versi yang terbaru, yaitu disini :
https://github.com/sufehmi/AhadPOS2/archive/master.zip

Selamat mencoba.

**Comment by mikhail2015** [comment]
Makasih pak, atas quick responnya. Kalo Saya coba seperti yang di
mod_barang errornya hilang pak. Apa nanti ada masalah kedepannya?

**Comment by mikhail2015** [comment]
pagi pak sufehmi,
saya coba di XAMPP versi 5.5.30 koq ga bisa jalannya ya?
ada pesan seperti ini :
*Deprecated*: mysql_connect(): The mysql extension is deprecated and will
be removed in the future: use mysqli or PDO instead in
*C:\xampp\htdocs\ahadpos2\config\config.php* on line *13*

*Warning*: mysql_connect(): Access denied for user 'root'@'localhost'
(using password: NO) in *C:\xampp\htdocs\ahadpos2\config\config.php* on
line *13*
Koneksi gagal

best regards,
iyan


2015-12-20 18:59 GMT+07:00 Iyan Mardiansyah <iyanmardiansyah@gmail.com>:

> Makasih pak, atas quick responnya. Kalo Saya coba seperti yang di
> mod_barang errornya hilang pak. Apa nanti ada masalah kedepannya?

**Comment by sufehmi** [comment]
Itu gagal karena isi file config.php belum benar.

Silakan diisi sesuai dengan username & password di MySQL / XAMPP Anda.

**Comment by mikhail2015** [comment]
tetap pak, saya sudah rubah di config.php nya.
pesan ini maksudnya apa ya pak " use mysqli or PDO"

saya coba gogling untuk mysql yang versi anyar koneksinya harus pake mysqli.
mohon penjelansannya


best regards,
iyan

2015-12-21 10:24 GMT+07:00 Harry Sufehmi <notifications@github.com>:

> Itu gagal karena isi file config.php belum benar.
>
> Silakan diisi sesuai dengan username & password di MySQL / XAMPP Anda.
>
>

**Comment by AbuMuhammad** [comment]
Untuk menghilangkan pesan Notice, Warning, & Deprecated yang ditampilkan XAMPP, bisa dengan merubah file /config/config.php
<code>
error_reporting(...;
</code>
menjadi
<code>
error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING);
</code>

**Comment by mikhail2015** [comment]
siang pak, error yg tadi sudah tidak muncul, sekarang keluar pesan koneksi
gagal karena saya menggunakan PHP 5 pak,
solusinya gimana pak?


best regards,
iyan

**Comment by AbuMuhammad** [comment]
Biasanya karena mysqlnya belum jalan, atau databasenya belum ada, atau
karena user & password mysqlnya salah.

**Comment by mikhail2015** [comment]
siang pak, sudah solve pak dan bisa login. tapi pada saat upgrade database
keluar pesan :

Current database version : 2.0.2
Current software version : 2.0.17

Checking database version 2.x.x
Upgrading database to version 2.0.x
Upgrading database to version 2.0.3
Gagal update db version, error:

itu kenapa ya pak.

best regards,
iyan

2015-12-21 13:59 GMT+07:00 Abu Muhammad <notifications@github.com>:

> Biasanya karena mysqlnya belum jalan, atau databasenya belum ada, atau
> karena user & password mysqlnya salah.

**Comment by AbuMuhammad** [comment]
Lanjutannya (pesan error) tolong di copy-paste ke sini.

Terlampir yang seharusnya muncul, dicoba pada 23 Des 2015 9:19 
![first-login](https://cloud.githubusercontent.com/assets/3438768/11970026/65346b6e-a956-11e5-855d-e927cb9cd423.png)

**Comment by AbuMuhammad** [comment]
Dengan menggunakan database awal:
https://github.com/sufehmi/AhadPOS2/blob/master/init-db-ahadpos2.mysql
