### ISSUE TITLE
Fitur Hutang dan Piutang

### ISSUE THREAD

**Issue by pancaz** [sufehmi/AhadPOS2#7]
Tolong ditambahkan fitur Hutang untuk transaksi pembelian dan fitur piutang untuk transaksi penjualan.
terima kasih

**Comment by sufehmi** [comment]
Halo, AhadPOS 2 sudah tidak dikembangkan lagi. 

Pada saat ini kami fokus ke AhadPOS 3, yang fiturnya sudah jauh lebih lengkap, termasuk yang diminta ini.

AhadPOS3 : https://github.com/AbuMuhammad/ap3

Terimakasih.
